### ISSUE TITLE
Error in regex_strip.py - all occurrences subbed instead of leading/trailing

### ISSUE THREAD

**Issue by WilliamVannuffelen** [zspatter/automate-the-boring-stuff#1]
Hello there,

I was taking a look at other people's implementation of ATBS Chapter 7 project 3 - create a regex-based version of the string .strip() method.

I like yours overall - matching what needs to be stripped then subbing it out is an elegant solution.
I noticed it has a small error in it and I figured I'd point it out.
As it stands, your implementation will match and strip all occurrences of the specified remove string, not just leading and trailing occurrences.

Test case '123home123home123' should return 'home123home', but currently it returns 'homehome'.

Changing line #18 to match how you stripped the whitespace characters resolves this issue:
old: return re.compile(str(remove)).sub('', text)
new: return re.compile(r'^{}*|{}*$'.format(remove,remove)).sub('', text)

I hope this helps.

Best regards,
Will

**Comment by zspatter** [comment]
William,

Nice catch, thanks for bringing this to my attention! While revisiting this implementation based on your feedback, I found another shortcoming. Repeated leading/trailing groups should be removed as well.

`123123home123home123123` should strip down to just `home123home`.
